### ISSUE TITLE
Total requests

### ISSUE THREAD

**Issue by ahmgeek** [vladvasiliu/kibana-prometheus-exporter-py#9]
Hey @vladvasiliu  👋 
I have a question, since everything is a gauge, 
would `sum_over_time(kibana_requests{status_code="200"[1d])` 
actually return the correct total number of `200` requests on a day?

**Comment by vladvasiliu** [comment]
Hi,
It *should*.
Note however that Kibana doesn't expose raw values, they are already aggregated.
For this sum to actually make sense, you should make sure that the aggregation interval is the same as your scraping interval.

**Comment by ahmgeek** [comment]
thanks a lot
